import PostsPage from "./posts/page";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="aliehlmi">
      <PostsPage />{" "}
    </div>
  );
}
