import type { Metadata } from "next";
import Footer from "../components/footer/Footer";
import NavBar from "../components/navBar/NavBar";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen container mx-auto">
      <NavBar />
      <main className="flex-grow py-4">{children}</main>
      <Footer />
    </div>
  );
}
